# File names are either absolute or relative to the parent folder of the
# vhdl_ls.toml file and supports glob-style patterns.
# This file is for code checking support for VHDL LS
[libraries]
matrix.files = [
  'tb/matrix/*.vhd',
]
work.files = [
  'src/hdl/*.vhd',
  'tb/Opallios_FPGA_tb.vhd',
]